### ISSUE TITLE
Full create command returns error

### ISSUE THREAD

**Issue by centrual** [framework7io/framework7-cli#1]
``` bash
f7 create subs_test_app top.auray.substest "Subscription Testing Suite" --template singleview
Creating new Framework7 app
Creating a new cordova project.
Downloading scripts & hooks
Error: EPERM: operation not permitted, rename 'C:\xampp\htdocs\1489460743747-9789895585609396\framework7-cli-scripts-master' -> 'C:\xampp\htdocs\subs_test_app\scripts'
  Downloading scripts & hooks ✓
module.js:472
    throw err;
    ^

Error: Cannot find module 'C:\xampp\htdocs\subs_test_app\scripts\hooks.json'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at C:\Users\oguzpc\AppData\Roaming\nvm\v7.7.2\node_modules\framework7-cli\commands.js:63:33
    at GithubDownloader.<anonymous> (C:\Users\oguzpc\AppData\Roaming\nvm\v7.7.2\node_modules\framework7-cli\utils\download-github.js:17:21)
    at emitNone (events.js:86:13)
    at GithubDownloader.emit (events.js:188:7)
    at C:\Users\oguzpc\AppData\Roaming\nvm\v7.7.2\node_modules\framework7-cli\node_modules\github-download\lib\github-download.js:134:19
    at next (C:\Users\oguzpc\AppData\Roaming\nvm\v7.7.2\node_modules\framework7-cli\node_modules\rimraf\rimraf.js:74:7)
```

I tested with and without administrator rights.

**Comment by regenesis-art** [comment]
I can second that. I also tried both with and without admin privs. Was testing with cordova 7.0.1.

**Comment by EleRam** [comment]
Same problem.
OS: Windows 10 x64

**Comment by megaterrarc** [comment]
Same problem.
OS: Windows 10 x64

**Comment by gitdward** [comment]
Same problem. 
OS: Windows x64.
npm: 5.5.1
Node: 8.9.0
Cordova: 8.0.0
Phonegap: 7.1.1

**Comment by ivanneira** [comment]
Same problem.

Windows 10 x64
node 8.9
cordova 6.3.1

windows 7 x64
node 6.11.1
cordova 6.3.1

ubuntu x64
node 6.11.1
cordova 8.0.0

**Comment by escaper01** [comment]
I'm facing the same problem :(
windows 10 x64
node 8.11.2
cordova 8.0.0

**Comment by aamir-pk** [comment]
Is there any solution to this problem?

**Comment by kozmanbalint** [comment]
Check v2 branch. It is in line with f7 v4.
