### ISSUE TITLE
Problem creating app (CLI) with cordova / capacitor on mac

### ISSUE THREAD

**Issue by jzraibi** [framework7io/framework7-cli#122]
while creating app on mac (CLI) the following happnes:
if i chose **capacitor** the script terminates before finishing the creation (while installing dev dependencies)
if i chose **cordova t**he script terminates while creating cordova project

please help

**Comment by itsthe1-apps** [comment]
[framework7-v6](https://blog.framework7.io/framework7-v6-d5b843abe8e7)

Based on the article, I've update NPM, Framework7-CLI and Framework7 in global. 

```
framework7-cli@4.0.2
npm -v 6.14.10
framework7 --version 4.0.2
```
Then tried to install by running `framework7 create --ui`. Choose PWA and Capacitor and CORE. Progress stoped at Creating Capacitor project.... tried many times.

✔ Generating package.json
✔ Creating required folders structure
✔ Installing NPM Dependencies
✔ Installing NPM Dev Dependencies
✔ Executing NPM Scripts
Creating Capacitor project (Please wait, it can take a while)

**Comment by AlwaysLoveme** [comment]
facing the same problem on my mac when upgrade to latest, any solutions?

**Comment by RaddishIoW** [comment]
Same here - when creating a Capacitor app via `framework7 create --ui`

The UI never progresses past "Installing NPM Dev Dependencies..."

**Comment by RaddishIoW** [comment]
I ran `framework7 create` and selected options for creating a Capacitor app, and got the following output:
```
✔ Generating package.json
✔ Creating required folders structure
✔ Installing NPM Dependencies
✖ Error installing NPM Dev Dependencies
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.10.0/libvips-8.10.0-darwin-x64.tar.br
internal/fs/utils.js:307
    throw err;
    ^

Error: EACCES: permission denied, copyfile '/var/folders/6c/12rsfjcx2gzbt51w4wkgf2ww0000gp/T/13047-libvips-8.10.0-darwin-x64.tar.br' -> '/Users/raddish/.npm/_libvips/libvips-8.10.0-darwin-x64.tar.br'
    at Object.copyFileSync (fs.js:1991:3)
    at WriteStream.<anonymous> (/Users/raddish/Development/Hayl/Hayl-Driver/node_modules/sharp/install/libvips.js:125:16)
    at WriteStream.emit (events.js:315:20)
    at emitCloseNT (internal/streams/destroy.js:87:10)
    at processTicksAndRejections (internal/process/task_queues.js:79:21) {
  errno: -13,
  syscall: 'copyfile',
  code: 'EACCES',
  path: '/var/folders/6c/12rsfjcx2gzbt51w4wkgf2ww0000gp/T/13047-libvips-8.10.0-darwin-x64.tar.br',
  dest: '/Users/raddish/.npm/_libvips/libvips-8.10.0-darwin-x64.tar.br'
}
warning: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: archive library: Release/nothing.a the table of contents is empty (no object file members in the library define global symbols)
../src/common.cc:24:10: fatal error: 'vips/vips8' file not found
#include <vips/vips8>
         ^~~~~~~~~~~~
1 error generated.
make: *** [Release/obj.target/sharp/src/common.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/raddish/.nvm/versions/node/v14.15.3/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Darwin 20.2.0
gyp ERR! command "/Users/raddish/.nvm/versions/node/v14.15.3/bin/node" "/Users/raddish/.nvm/versions/node/v14.15.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/raddish/Development/Hayl/Hayl-Driver/node_modules/sharp
gyp ERR! node -v v14.15.3
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm WARN optimize-css-assets-webpack-plugin@5.0.4 requires a peer of webpack@^4.0.0 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.26.3 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sharp@0.26.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

I'm on macOS 11.1, Node v 14.15.0.

**Comment by RaddishIoW** [comment]
Still getting this error with framework-cli v.4.0.8

**Comment by RaddishIoW** [comment]
I managed to get past my problem by manually installing vips with homebrew:
`brew install vips`

I could then run `f7 create`

**Comment by scriptPilot** [comment]
Same issue here (MacBook Air M1) - Solution with "brew install vips" ended in another error, coming from sharp module. There are multiple issues like this posted over the last couple of weeks. Maybe there is a chance to remove the module from the CLI somehow?
