### ISSUE TITLE
Template7 helpers error

### ISSUE THREAD

**Issue by GuillaumeBiton** [framework7io/framework7-cli#13]
Hi,

environment : framework7-cli webpack

I register Template7 helpers in "app.js" and declare it in "template7-helpers-list.js" but When I try to test I get this error :

`
ERROR in ./src/pages/stories.f7.html
Module build failed (from ./node_modules/framework7-component-loader/lib/index.js):
Error: Template7: Missing helper: "pluralize"
    at Template7Class.compile (/Users/guillaumebiton/Documents/Github/HackerNews7/node_modules/template7/dist/template7.js:584:17)
    at getCompileFn (/Users/guillaumebiton/Documents/Github/HackerNews7/node_modules/template7/dist/template7.js:525:37)
    at Template7Class.compile (/Users/guillaumebiton/Documents/Github/HackerNews7/node_modules/template7/dist/template7.js:582:295)
    at getCompileFn (/Users/guillaumebiton/Documents/Github/HackerNews7/node_modules/template7/dist/template7.js:525:37)
    at Template7Class.compile (/Users/guillaumebiton/Documents/Github/HackerNews7/node_modules/template7/dist/template7.js:582:295)
    at getCompileFn (/Users/guillaumebiton/Documents/Github/HackerNews7/node_modules/template7/dist/template7.js:525:37)
    at Template7Class.compile (/Users/guillaumebiton/Documents/Github/HackerNews7/node_modules/template7/dist/template7.js:582:295)
    at Function.compile (/Users/guillaumebiton/Documents/Github/HackerNews7/node_modules/template7/dist/template7.js:649:21)
    at Object.loader (/Users/guillaumebiton/Documents/Github/HackerNews7/node_modules/framework7-component-loader/lib/index.js:161:43)
 @ ./src/js/routes.js 3:0-51 13:19-30 20:21-32
 @ ./src/js/app.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 (webpack)/hot/dev-server.js ./src/js/app.js
`

Should I declare them somewhere else ?

**Comment by nolimits4web** [comment]
Hi, what is in your `template7-helpers-list.js`?

**Comment by nolimits4web** [comment]
Fixed with https://github.com/framework7io/framework7-cli/commit/6342189fbca188ee5e93e9c858df0a1fe23c4177

Just move `template7-helpers-list.js` from `/src/js/` to just `/src/` folder
