### ISSUE TITLE
"framework7 create" fails installing deps

### ISSUE THREAD

**Issue by albertosantini** [framework7io/framework7-cli#14]
* Framework7 version: 2.0.1
* Platform and Target: [e.g. iOS 11 Cordova app, or Android 8 Chrome browser]
* Live Link or JSFiddle: PREFERABLY _(IF YOU WANT YOUR ISSUE TO BE RESOLVED ASAP)_. You can start from forking the following JSFiddle template: [JSFiddle](https://jsfiddle.net/nolimits4web/o2ejupu1/)

### Describe the bug
Executing `framework7 create` inside an empty folder, the installation of the deps fails.

### To Reproduce
```
$ framework7 create
√ All good, you have latest framework7-cli version.
? What type of the app are you targeting? Cordova + PWA (Progressive Web App)
? App (project) name: TinabaNext
? App package (Bundle ID): it.tinaba.tinabanext
? Target Cordova platform: Android
? What type of framework do you prefer? Framework7 Core
? Choose starter template: Tabbed Views (Tabs)
? Should we setup project with bundler? Webpack (recommended)
? Do you want to setup CSS Pre-Processor No, i am good with CSS
? Do you want to specify custom theme color? No, use default color theme
√ Generating package.json
√ Creating required folders structure
√ Installing NPM Dependencies
× Error installing NPM Dev Dependencies
npm ERR! Unexpected end of JSON input while parsing near '...t-spread":"7.0.0-beta'
```

### Expected behavior
I expect the creation of the project.

### Actual Behavior
The project is half-baked.

### Screenshots
n.a.

### Additional context
npm log:

```
...
56 silly pacote tag manifest for style-loader@latest fetched in 867ms
57 http fetch GET 304 https://registry.npmjs.org/uglifyjs-webpack-plugin 887ms (from cache)
58 silly pacote tag manifest for uglifyjs-webpack-plugin@latest fetched in 889ms
59 timing stage:rollbackFailedOptional Completed in 0ms
60 timing stage:runTopLevelLifecycles Completed in 1254ms
61 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '...t-spread":"7.0.0-beta'
61 verbose stack     at JSON.parse (<anonymous>)
61 verbose stack     at parseJson (C:\Users\XXX\AppData\Roaming\npm\node_modules\npm\node_modules\json-parse-better-errors\index.js:7:17)
61 verbose stack     at consumeBody.call.then.buffer (C:\Users\XXX\AppData\Roaming\npm\node_modules\npm\node_modules\node-fetch-npm\src\body.js:96:50)
61 verbose stack     at process._tickCallback (internal/process/next_tick.js:68:7)
...
```

**Comment by nolimits4web** [comment]
Make sure you have latest Node.js version (https://nodejs.org/en/) and try again

**Comment by albertosantini** [comment]
I have been using the latest LTS.

```

$ node -v
v10.15.1

$ npm -v
6.8.0
```

**Comment by ghost** [comment]
Having the same issue here, although for a different reason. For some reason npm is getting EACCES errors even though the entire project folder is owned by the operating user. Maybe it's because of snap? Debug logs annoyingly don't log what file the operation is being attempted on though
```bash
$ node -v
v11.10.0
$ npm -v
6.8.0
$ f7 create
✔ All good, you have latest framework7-cli version.
? What type of the app are you targeting? PWA (Progressive Web App)
? App (project) name: App
? What type of framework do you prefer? Framework7 Core
? Choose starter template: Single View
? Should we setup project with bundler? No bundler
? Do you want to specify custom theme color? Yes, i want to specify my brand col
or
? Enter custom theme color in HEX format (e.g. ff0000) FF0000
✔ Generating package.json
✔ Creating required folders structure
✖ Error installing NPM Dependencies

$
```
[debug.log](https://gist.github.com/kakolisgay/a66a682f944e93ae798e19950fe599ce)

When installing the dependencies manually everything goes fine
```bash
$ npm install framework7 dom7 template7 framework7-icons --save
npm WARN lifecycle The node binary used for scripts is /snap/bin/node but npm is using /snap/node/1684/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> framework7@4.0.5 postinstall ~/Project/node_modules/framework7
> node -e "console.log('\u001b[35m\u001b[1mLove Framework7? Support project by donating or pledging on patreon:\u001b[22m\u001b[39m\n > \u001b[32mhttps://patreon.com/vladimirkharlampidi\u001b[0m\n')"

Love Framework7? Support project by donating or pledging on patreon:
 > https://patreon.com/vladimirkharlampidi

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN project No description
npm WARN project No repository field.
npm WARN project No license field.

+ template7@1.4.1
+ framework7-icons@2.2.0
+ framework7@4.0.5
+ dom7@2.1.3
added 6 packages from 1 contributor and audited 10 packages in 3.113s
found 0 vulnerabilities

```

**Comment by albertosantini** [comment]
@kakolisgay Well, it seems different.

- You are running on Linux box, I have been running on Windows one.
- Different Node.js version
- Different error, as you said.
- f7 project options are different: mine is PWA+Cordova+Webpack, yours is PWA+no bundler.

And for my issue, I think, the matter is related to Webpack, because setting the project without the bundler, the installation works fine.

In your case, I think, you should investigate on Linux setup.
For sure the manual installation is confusing, because it is ok.
Check if you start from the same context: same folder permission, same empty folder and so on.

**Comment by ghost** [comment]
It happens with any option, I'm pretty sure it's an npm problem though.
Doute it'll be fixed in a timely manner

**Comment by srbala** [comment]
@kakolisgay @albertosantini Please confirm if you still have issues, please make sure to update Framework-cli, before it.

**Comment by mansourcodes** [comment]
Edit: 
I have solve it by running the code recommended on the error it self.
npm ERR!   **sudo chown -R 501:20 "/Users/alnassre/.npm"**


-------

Same Error Here 

**$ framework7 create** 
```
✔ All good, you have latest framework7-cli version.
✖ Framework7 project already set up in current directory
alnassres-MacBook-Pro:aldreh alnassre$ framework7 create 
✔ All good, you have latest framework7-cli version.
? What type of the app are you targeting? Simple web app
? App (project) name: Aldreh
? What type of framework do you prefer? Framework7 with Vue.js
? Choose starter template: Single View
? Do you want to setup CSS Pre-Processor SCSS (SASS)
? Do you want to specify custom theme color? No, use default color theme
? Do you want to include Framework7 Icons and Material Icons icon fonts? Yes, include icon fonts
✔ Generating package.json
✔ Creating required folders structure
✔ Installing NPM Dependencies
✖ Error installing NPM Dev Dependencies
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! code EACCES
npm ERR! syscall open
npm ERR! path /Users/alnassre/.npm/_cacache/index-v5/21/19/e01e4bd45cdb8d7472547943a8847cc66165a3c8f56e0869995f5b139824
npm ERR! errno -13
npm ERR! 
npm ERR! Your cache folder contains root-owned files, due to a bug in
npm ERR! previous versions of npm which has since been addressed.
npm ERR! 
npm ERR! To permanently fix this problem, please run:
npm ERR!   sudo chown -R 501:20 "/Users/alnassre/.npm"

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/alnassre/.npm/_logs/2020-07-17T21_19_14_503Z-debug.log
```

**$npm -v**
6.14.6
**$ node -v**
v10.16.0
**$framework7 -V**
3.4.2

using macOS
