### ISSUE TITLE
Error while

### ISSUE THREAD

**Issue by scriptPilot** [framework7io/framework7-cli#143]
- Installed CLI in folder (not global)
- Run CLI without UI
- Select simple web app / blank / F7 Svelte + Icons
  
    ✔ Generating package.json
    ✔ Creating required folders structure
    ✔ Installing NPM Dependencies
    ✔ Installing NPM Dev Dependencies
    ✔ Executing NPM Scripts
    ⠋ Creating project filesnode:fs:1057
      handleErrorFromBinding(ctx);
      ^
    
    Error: ENOENT: no such file or directory, scandir '/Users/Dennis/Documents/GitHub/f7-svelte-contacts/node_modules/framework7-cli/create/templates/common/icons'
        at Object.readdirSync (node:fs:1057:3)
        at Object.readdirSync (/Users/Dennis/Documents/GitHub/f7-svelte-contacts/node_modules/framework7-cli/utils/fs-extra.js:12:15)
        at module.exports (/Users/Dennis/Documents/GitHub/f7-svelte-contacts/node_modules/framework7-cli/create/templates/copy-assets.js:116:9)
        at module.exports (/Users/Dennis/Documents/GitHub/f7-svelte-contacts/node_modules/framework7-cli/create/index.js:142:23)
        at processTicksAndRejections (node:internal/process/task_queues:94:5)
        at async Command.<anonymous> (/Users/Dennis/Documents/GitHub/f7-svelte-contacts/node_modules/framework7-cli/index.js:56:7) {
      errno: -2,
      syscall: 'scandir',
      code: 'ENOENT',
      path: '/Users/Dennis/Documents/GitHub/f7-svelte-contacts/node_modules/framework7-cli/create/templates/common/icons'
    }

**Comment by nolimits4web** [comment]
It is not indented to be used as local package. Install it globally or use npx
