### ISSUE TITLE
Shell command exit with non zero code: 243 (Ubuntu)

### ISSUE THREAD

**Issue by heynedim** [framework7io/framework7-cli#147]
# Framework7 Ubuntu 20.04

I exported to last line to global packages and frameworks in .bashrc.
.bashrc
`export PATH="$HOME/.npm-packages/bin:$PATH"`

### When i use `framework7 create` or `framework7 create --ui`
<pre><font color="#4E9A06"><b>jack5341@Kitty</b></font>:<font color="#3465A4"><b>~/Documents/projects/test</b></font>$ framework7 create
<font color="#4E9A06">✔</font> All good, you have latest framework7-cli version.
<font color="#4E9A06">?</font> <b>What type of the app are you targeting?</b> <font color="#06989A">Simple web app</font>
<font color="#4E9A06">?</font> <b>App (project) name:</b> <font color="#06989A">My App</font>
<font color="#4E9A06">?</font> <b>What type of framework do you prefer?</b> <font color="#06989A">Framework7 with React</font>
<font color="#4E9A06">?</font> <b>Choose starter template:</b> <font color="#06989A">Blank</font>
<font color="#4E9A06">?</font> <b>Do you want to setup CSS Pre-Processor</b> <font color="#06989A">No, i am good with CSS</font>
<font color="#4E9A06">?</font> <b>Do you want to specify custom theme color?</b> <font color="#06989A">No, use default color theme</font>
<font color="#4E9A06">?</font> <b>Do you want to include Framework7 Icons and Material Icons icon fonts?</b> <font color="#06989A">Yes, in</font>
<font color="#06989A">clude icon fonts</font>
<font color="#4E9A06">✔</font> Generating package.json
<font color="#4E9A06">✔</font> Creating required folders structure
<font color="#CC0000">✖</font> Error installing NPM Dependencies

<font color="#CC0000">Error: Shell command exit with non zero code: 243</font>
</pre>

## I can see it in my .npm-global folder to

![image](https://user-images.githubusercontent.com/53150440/116392739-18e54d80-a821-11eb-8eab-3da075c170fd.png)

**Comment by heynedim** [comment]
### I added console.log for error at index.js (line 72)

<pre><font color="#4E9A06">⠼</font> Installing NPM Dependencies <font color="#555753">(Please wait, it can take a while)</font>Error: Shell command exit with non zero code: 243
    at ChildProcess.&lt;anonymous&gt; (/home/jack5341/Documents/projects/framework7-cli/node_modules/<u style="text-decoration-style:single">exec-sh</u>/lib/exec-sh.js:73:15)
<font color="#555753">    at ChildProcess.emit (events.js:315:20)</font>
<font color="#555753">    at maybeClose (internal/child_process.js:1048:16)</font>
<font color="#555753">    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)</font> {
  code: <font color="#C4A000">243</font>,
  stdout: <font color="#4E9A06">&apos;&apos;</font>,
  stderr: <font color="#4E9A06">&apos;&apos;</font>
}
<font color="#CC0000">✖</font> Error installing NPM Dependencies

<font color="#CC0000">Error: Shell command exit with non zero code: 243</font>
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> <font color="#75507B">code</font> ELIFECYCLE
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> <font color="#75507B">errno</font> 1
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> framework7-cli@4.0.8 start: `node index.js create`
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> Exit status 1
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> 
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> Failed at the framework7-cli@4.0.8 start script.
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> This is probably not a problem with npm. There is likely additional logging output above.

<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> A complete log of this run can be found in:
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span>     /home/jack5341/.npm/_logs/2021-04-29T02_40_53_478Z-debug.log
</pre>
