### ISSUE TITLE
Could not resolve "framework7/lite"

### ISSUE THREAD

**Issue by lroal** [framework7io/framework7-cli#190]
I am running the vue/vite setup with version 7. And get this error when running:
```
X [ERROR] Could not resolve "framework7/lite"

    ../node_modules/framework7-vue/esm/shared/f7.js:2:23:
      2 │ import Framework7 from 'framework7/lite';
        ╵                        ~~~~~~~~~~~~~~~~~

  You can mark the path "framework7/lite" as external to exclude it from the bundle, which will
  remove this error.

09:06:11 [vite] error while updating dependencies:
Error: Build failed with 2 errors:
../node_modules/framework7-vue/esm/shared/f7.js:2:23: ERROR: Could not resolve "framework7/lite"
../node_modules/framework7-vue/esm/shared/plugin.js:1:23: ERROR: Could not resolve "framework7/lite"     
    at failureErrorWithLog (C:\Users\lars.roald\repos\f7Client\node_modules\esbuild\lib\main.js:1603:15) 
    at C:\Users\lars.roald\repos\f7Client\node_modules\esbuild\lib\main.js:1249:28
    at runOnEndCallbacks (C:\Users\lars.roald\repos\f7Client\node_modules\esbuild\lib\main.js:1034:63)   
    at buildResponseToResult (C:\Users\lars.roald\repos\f7Client\node_modules\esbuild\lib\main.js:1247:7)
    at C:\Users\lars.roald\repos\f7Client\node_modules\esbuild\lib\main.js:1356:14
    at C:\Users\lars.roald\repos\f7Client\node_modules\esbuild\lib\main.js:666:9
    at handleIncomingPacket (C:\Users\lars.roald\repos\f7Client\node_modules\esbuild\lib\main.js:763:9)  
    at Socket.readFromStdout (C:\Users\lars.roald\repos\f7Client\node_modules\esbuild\lib\main.js:632:7)
    at Socket.emit (node:events:526:28)
    at addChunk (node:internal/streams/readable:315:12)
```

**Comment by nolimits4web** [comment]
That is something with your local npm cache, there is no references to /esm/ folder in v7

**Comment by lroal** [comment]
I cleaned my cache. Did a fresh npm install and problem is still there.

**Comment by lroal** [comment]
Forget it. It works now.
