### ISSUE TITLE
Error when run framework7 create

### ISSUE THREAD

**Issue by ezani92** [framework7io/framework7-cli#24]
Death-Mac:ecommerce_app Macintosh$ sudo framework7 create
/usr/local/lib/node_modules/framework7-cli/node_modules/bindings/bindings.js:135
  throw err;
  ^

Error: Could not locate the bindings file. Tried:
 → /usr/local/lib/node_modules/framework7-cli/node_modules/sharp/build/sharp.node
 → /usr/local/lib/node_modules/framework7-cli/node_modules/sharp/build/Debug/sharp.node
 → /usr/local/lib/node_modules/framework7-cli/node_modules/sharp/build/Release/sharp.node
 → /usr/local/lib/node_modules/framework7-cli/node_modules/sharp/out/Debug/sharp.node
 → /usr/local/lib/node_modules/framework7-cli/node_modules/sharp/Debug/sharp.node
 → /usr/local/lib/node_modules/framework7-cli/node_modules/sharp/out/Release/sharp.node
 → /usr/local/lib/node_modules/framework7-cli/node_modules/sharp/Release/sharp.node
 → /usr/local/lib/node_modules/framework7-cli/node_modules/sharp/build/default/sharp.node
 → /usr/local/lib/node_modules/framework7-cli/node_modules/sharp/compiled/8.9.1/darwin/x64/sharp.node
 → /usr/local/lib/node_modules/framework7-cli/node_modules/sharp/addon-build/release/install-root/sharp.node
 → /usr/local/lib/node_modules/framework7-cli/node_modules/sharp/addon-build/debug/install-root/sharp.node
 → /usr/local/lib/node_modules/framework7-cli/node_modules/sharp/addon-build/default/install-root/sharp.node
 → /usr/local/lib/node_modules/framework7-cli/node_modules/sharp/lib/binding/node-v57-darwin-x64/sharp.node
    at bindings (/usr/local/lib/node_modules/framework7-cli/node_modules/bindings/bindings.js:126:9)
    at Object.<anonymous> (/usr/local/lib/node_modules/framework7-cli/node_modules/sharp/lib/constructor.js:10:34)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/framework7-cli/node_modules/sharp/lib/index.js:3:15)

**Comment by smanczak** [comment]
And generate-assets - It doesn't work either.

UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'indexOf' of undefined
    at generateAssets

**Comment by ang3lx** [comment]
same here.. generate-assets doesn't work

**Comment by smanczak** [comment]
Changing package.json from new version and all is great :)

**Comment by emad-sure** [comment]
Same Issue here , any solution @seba316d  @ang3lx 
Node Version v12.10.0

![2019-09-30_19-34](https://user-images.githubusercontent.com/53175321/65901911-72716600-e3b9-11e9-9fa1-bf9d20eed0c7.png)

**Comment by brettsprad** [comment]
Same here:

![image](https://user-images.githubusercontent.com/47604288/70105239-57aabe80-1694-11ea-8a70-462cd4efccfe.png)

I've tried:
-clearing cache: npm cache clean --force
-reinstalling sharp: npm install sharp --unsafe-perm
-deleting node_modules folder & reinstalling node: npm install

...but nothing works.
