### ISSUE TITLE
Error from framework7-cli/index.js:59

### ISSUE THREAD

**Issue by wwhyte** [framework7io/framework7-cli#40]
When I run framework7 from the command line on my Mac, no matter what the arguments, I get the following error message

/usr/local/lib/node_modules/framework7-cli/index.js:59
          ...opts,
          ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3

It seems like my Javascript parser doesn't understand the "...opts" syntax. This probably isn't a bug in f7 itself but if anyone could suggest how to resolve it I'd be very grateful.

**Comment by nolimits4web** [comment]
You need to update Node.js to latest https://nodejs.org/en/
