### ISSUE TITLE
Creating project crash on windows

### ISSUE THREAD

**Issue by Tarekajaj** [framework7io/framework7-cli#56]
I'm facing the following error when creating a new project, after updating to latest version,

```
F:\test>framework7 create
- Checking for available updates...(node:24068) ExperimentalWarning: The fs.promises API is experimental
√ All good, you have latest framework7-cli version.
? What type of the app are you targeting? Cordova app (targets native iOS and Android apps, or native desktop app with E
lectron)
? App (project) name: My App
? App package (Bundle ID): io.framework7.myapp
? Target Cordova platform: Android
? What type of framework do you prefer? Framework7 Core
? Choose starter template: Single View
? Should we setup project with bundler? Webpack (recommended)
? Do you want to setup CSS Pre-Processor SCSS (SASS)
? Do you want to specify custom theme color? No, use default color theme
? Do you want to include Framework7 Icons and Material Icons icon fonts? Yes, include icon fonts
√ Generating package.json
√ Creating required folders structure
√ Installing NPM Dependencies
√ Installing NPM Dev Dependencies
× Error executing NPM Scripts
Cannot copy `'./node_modules/framework7-icons/fonts/*.*'`: the file doesn't exist
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-app@1.0.0 postinstall: `cpy './node_modules/framework7-icons/fonts/*.*' './src/fonts/'`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the my-app@1.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Roaming\npm-cache\_logs\2019-12-10T08_24_45_893Z-debug.log
```
Please advise,

Content of 2019-12-10T08_24_45_893Z-debug.log
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\user\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'postinstall' ]
2 info using npm@5.3.0
3 info using node@v10.1.0
4 verbose run-script [ 'postinstall' ]
5 info lifecycle my-app@1.0.0~postinstall: my-app@1.0.0
6 verbose lifecycle my-app@1.0.0~postinstall: unsafe-perm in lifecycle true
7 verbose lifecycle my-app@1.0.0~postinstall: PATH: C:\Users\user\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;F:\test\node_modules\.bin;C:\Users\user\.windows-build-tools\python27\;C:\Users\user\.windows-build-tools\python27\Scripts;C:\Program Files\Docker\Docker\Resources\bin;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files (x86)\AMD\ATI.ACE\Core-Static;C:\xampp\php;C:\Program Files\Git\cmd;C:\Program Files\PuTTY\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\ProgramData\chocolatey\bin;C:\WINDOWS\System32\OpenSSH\;C:\Ruby24-x64\bin;C:\Program Files\Ruby24-x64\bin;C:\Users\user\AppData\Local\Microsoft\WindowsApps;C:\Users\user\AppData\Roaming\Composer\vendor\bin;C:\Users\user\AppData\Roaming\npm;C:\Program Files\Java\jdk1.8.0_131\bin;C:\Users\user\Android\sdk\build-tools\25.0.3;C:\Users\user\Android\sdk\platform-tools;C:\Program Files (x86)\Nmap;C:\Program Files (x86)\FontForgeBuilds\bin;T:\xampp\mysql\bin;C:\Program Files (x86)\GnuWin32\bin;C:\flutter\bin;T:\bpm\a;C:\Program Files\nodejs\;C:\Program Files (x86)\Yarn\bin\;C:\HashiCorp\Vagrant\bin;C:\Program Files (x86)\Common Files\Acronis\SnapAPI\;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files\dotnet\;C:\PostgreSQL\pg10\bin;C:\Users\user\AndroidStudioProjects\android-ndk-r18b;C:\ProgramData\ComposerSetup\bin;;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\CMake\bin;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Users\user\scoop\shims;C:\Ruby24-x64\bin;C:\Program Files\Ruby24-x64\bin;C:\Users\user\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Java\jdk1.8.0_131\bin;C:\Users\user\Android\sdk\build-tools\25.0.3;C:\Users\user\Android\sdk\platform-tools;C:\Program Files (x86)\Nmap;C:\Program Files (x86)\FontForgeBuilds\bin;T:\xampp\mysql\bin;C:\Program Files (x86)\GnuWin32\bin;T:\bpm\apache-ant-1.10.3\bin;C:\apache-maven-3.6.2\bin;C:\Program Files\Oracle\VirtualBox;C:\Program Files\Docker\Docker\resources\bin;C:\Users\user\AppData\Local\Microsoft\WindowsApps;C:\Users\user\AppData\Roaming\npm;C:\Users\user\AppData\Local\Yarn\bin;C:\Users\user\AndroidStudioProjects\android-ndk-r18b;C:\flutter\bin;C:\Users\user\Downloads\icons\New folder\woff2\out\Release;
8 verbose lifecycle my-app@1.0.0~postinstall: CWD: F:\test
9 silly lifecycle my-app@1.0.0~postinstall: Args: [ '/d /s /c',
9 silly lifecycle   'cpy \'./node_modules/framework7-icons/fonts/*.*\' \'./src/fonts/\'' ]
10 silly lifecycle my-app@1.0.0~postinstall: Returned: code: 1  signal: null
11 info lifecycle my-app@1.0.0~postinstall: Failed to exec postinstall script
12 verbose stack Error: my-app@1.0.0 postinstall: `cpy './node_modules/framework7-icons/fonts/*.*' './src/fonts/'`
12 verbose stack Exit status 1
12 verbose stack     at EventEmitter.<anonymous> (C:\Users\user\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:289:16)
12 verbose stack     at EventEmitter.emit (events.js:182:13)
12 verbose stack     at ChildProcess.<anonymous> (C:\Users\user\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
12 verbose stack     at ChildProcess.emit (events.js:182:13)
12 verbose stack     at maybeClose (internal/child_process.js:957:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:246:5)
13 verbose pkgid my-app@1.0.0
14 verbose cwd F:\test
15 verbose Windows_NT 10.0.18362
16 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\user\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "postinstall"
17 verbose node v10.1.0
18 verbose npm  v5.3.0
19 error code ELIFECYCLE
20 error errno 1
21 error my-app@1.0.0 postinstall: `cpy './node_modules/framework7-icons/fonts/*.*' './src/fonts/'`
21 error Exit status 1
22 error Failed at the my-app@1.0.0 postinstall script.
22 error This is probably not a problem with npm. There is likely additional logging output above.
23 verbose exit [ 1, true ]
```

**Comment by Tarekajaj** [comment]
Origin of the issue sindresorhus/cpy-cli#22
