### ISSUE TITLE
V2: Error while creating cordova project

### ISSUE THREAD

**Issue by Soean** [framework7io/framework7-cli#8]
````
➜  age git:(master) ✗ framework7 create
✔ All good, you have latest framework7-cli version.
? What type of the app are you targeting? Cordova + PWA (Progressive Web App)
? App (project) name: AGE
? App package (Bundle ID): io.framework7.myapp
? Target Cordova platform: (Press <space> to select, <a> to toggle all, <i> to invert selection)iOS, Android
? What type of framework do you prefer? Framework7 with Vue.js
? Choose starter template: Split View (Split Panel)
? Do you want to specify custom theme color? No, use default color theme
✔ Generating package.json
✔ Creating required folders structure
✔ Installing NPM Dependencies
✔ Installing NPM Dev Dependencies
⠏ Creating Cordova project (Please wait, it can take a while)(node:13646) UnhandledPromiseRejectionWarning: TypeError: l.trimStart is not a function
    at str.split.map (/Users/xxx/.nvm/versions/node/v9.4.0/lib/node_modules/framework7-cli/create-app/utils/indent.js:19:53)
    at Array.map (<anonymous>)
    at module.exports (/Users/xxx/.nvm/versions/node/v9.4.0/lib/node_modules/framework7-cli/create-app/utils/indent.js:15:6)
    at module.exports (/Users/xxx/.nvm/versions/node/v9.4.0/lib/node_modules/framework7-cli/create-app/templates/generate-config-xml.js:4:10)
    at Promise (/Users/xxx/.nvm/versions/node/v9.4.0/lib/node_modules/framework7-cli/create-app/templates/create-cordova.js:39:68)
    at <anonymous>
(node:13646) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:13646) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
⠙ Creating Cordova project (Please wait, it can take a while)
````

I startet a new app via the CLI V2, but after the error nothing happens. has anyone an idea?

**Comment by nolimits4web** [comment]
You need to update node.js to latest version (must be 10+)

**Comment by Soean** [comment]
Thanks, of course :)
