### ISSUE TITLE
npm start error

### ISSUE THREAD

**Issue by lws68825** [framework7io/framework7-cli#80]
Hi,
When I ran npm start to a framework7 project, I got this error:
ValidationError: Invalid options object. Copy Plugin has been initialized using an options object that does not match the API schema.
 - options[0] misses the property 'patterns'. Should be:
   [non-empty string | object { from, to?, context?, globOptions?, toType?, force?, flatten?, transform?, cacheTransform?, transformPath?, noErrorOnMissing? }, ...] (should not have fewer than 1 item)
 - options[1] misses the property 'patterns'. Should be:
   [non-empty string | object { from, to?, context?, globOptions?, toType?, force?, flatten?, transform?, cacheTransform?, transformPath?, noErrorOnMissing? }, ...] (should not have fewer than 1 item)
    at validate (/home/lws/nodeapps/demo1/node_modules/schema-utils/dist/validate.js:96:11)
    at new CopyPlugin (/home/lws/nodeapps/demo1/node_modules/copy-webpack-plugin/dist/index.js:24:30)
    at Object.<anonymous> (/home/lws/nodeapps/demo1/build/webpack.config.js:192:5)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at WEBPACK_OPTIONS (/home/lws/nodeapps/demo1/node_modules/webpack-cli/bin/utils/convert-argv.js:114:13)
    at requireConfig (/home/lws/nodeapps/demo1/node_modules/webpack-cli/bin/utils/convert-argv.js:116:6)
    at /home/lws/nodeapps/demo1/node_modules/webpack-cli/bin/utils/convert-argv.js:123:17
    at Array.forEach (<anonymous>)
    at module.exports (/home/lws/nodeapps/demo1/node_modules/webpack-cli/bin/utils/convert-argv.js:121:15)
    at Object.<anonymous> (/home/lws/nodeapps/demo1/node_modules/webpack-dev-server/bin/webpack-dev-server.js:84:40)
    at Module._compile (internal/modules/cjs/loader.js:1138:30) {
  errors: [
    {
      keyword: 'required',
      dataPath: '[0]',
      schemaPath: '#/required',
      params: [Object],
      message: "should have required property 'patterns'",
      schema: [Object],
      parentSchema: [Object],
      data: [Object],
      children: [Array]
    },
    {
      keyword: 'required',
      dataPath: '[1]',
      schemaPath: '#/required',
      params: [Object],
      message: "should have required property 'patterns'",
      schema: [Object],
      parentSchema: [Object],
      data: [Object],
      children: [Array]
    }
  ],
  schema: {
    definitions: { ObjectPattern: [Object], StringPattern: [Object] },
    type: 'object',
    additionalProperties: false,
    properties: { patterns: [Object], options: [Object] },
    required: [ 'patterns' ]
  },
  headerName: 'Copy Plugin',
  baseDataPath: 'options',
  postFormatter: null
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! demo1@1.0.0 dev: `cross-env NODE_ENV=development webpack-dev-server --config ./build/webpack.config.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the demo1@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/abc/.npm/_logs/2020-06-01T02_40_02_975Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! demo1@1.0.0 start: `npm run dev`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the demo1@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/abc/.npm/_logs/2020-06-01T02_40_03_039Z-debug.log

can anyone help me on this? the project is created with framework7-cli@2.3.3, node v12.17.0, ubuntu 18.04.

**Comment by lws68825** [comment]
After upgrade to framework-cli@3.3.2, everything works well.
