### ISSUE TITLE
Error Error: spawn cmd ENOENT when running framework7 create --ui

### ISSUE THREAD

**Issue by delebash** [framework7io/framework7-cli#86]
Windows 10
Node 12.18.1
Framework 7 cli 3.4.2

To reproduce:

1) npm install -g framework7-cli
2) framework7 create --ui 

Tried alternate port framework7 create --ui --port 8001

Error:

D:\github_projects\facemesh-f7>framework7 create --ui --port 8001
√ All good, you have latest framework7-cli version.
√ Launching Framework7 UI server

Framework7 CLI UI is running on http://localhost:8001 (CTRL + C to exit)
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: spawn cmd ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn cmd',
  path: 'cmd',
  spawnargs: [ '/c', 'start', '""', '/b', 'http://localhost:8001/create/' ]
}

**Comment by delebash** [comment]
I have never had an issue running npm and do not have an issue with any other project.  I found an answer on the web to Add C:\Windows\System32 to the global PATH environment variable and this fixed the problem for me.  I found the answer on stackoverflow  see https://stackoverflow.com/questions/57054403/problem-with-npm-start-error-spawn-cmd-enoent.  If anyone has an answer as to why this is happening I would appreciate it.  Thanks

**Comment by srbala** [comment]
@delebash issue seems user specific, not reproduceable. please close
