### ISSUE TITLE
Unhandled promise rejection ENOENT create/templates/common/icons

### ISSUE THREAD

**Issue by timdp** [framework7io/framework7-cli#93]
Just getting started with the CLI:

```
$ mkdir project
$ cd project
$ yarn init -y
$ yarn add framework7-cli -D
$ yarn run framework7 create
? What type of the app are you targeting? Simple web app
? App (project) name: project
? What type of framework do you prefer? Framework7 with React
? Choose starter template: Single View
? Do you want to setup CSS Pre-Processor No, i am good with CSS
? Do you want to specify custom theme color? No, use default color theme
? Do you want to include Framework7 Icons and Material Icons icon fonts? Yes, include icon fonts
✔ Generating package.json
✔ Creating required folders structure
✔ Installing NPM Dependencies
✔ Installing NPM Dev Dependencies
✔ Executing NPM Scripts
```

And then this happened:

```
Creating project files(node:504661) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, scandir 'project/node_modules/framework7-cli/create/templates/common/icons'
    at Object.readdirSync (fs.js:981:3)
    at Object.readdirSync (project/node_modules/framework7-cli/utils/fs-extra.js:12:15)
    at module.exports (project/node_modules/framework7-cli/create/templates/copy-assets.js:115:9)
    at module.exports (project/node_modules/framework7-cli/create/index.js:125:23)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Command.<anonymous> (project/node_modules/framework7-cli/index.js:56:7)
```

The animation for "Creating project files" kept going but I assume it actually died, so I hit Ctrl-C.

Node v14.7.0, Yarn v1.22.5, Ubuntu 20.04.

**Comment by nolimits4web** [comment]
CLI must be installed globally https://framework7.io/cli/installation.html
