### ISSUE TITLE
Svelte script error on new project generations

### ISSUE THREAD

**Issue by srbala** [framework7io/framework7-cli#96]
Using CLI for Svelte is worked well until few weeks back. currently it getting script error as follows. Is anyone else facing this issues now (Oct 11).

```
2519 http fetch GET 304 https://registry.npmjs.org/svelte 45ms (from cache)
2520 silly fetchPackageMetaData error for svelte@3.25.3 Unexpected end of JSON input while parsing near '...:"^0.24.0","mocha":"3'
2521 timing stage:rollbackFailedOptional Completed in 1ms
2522 timing stage:runTopLevelLifecycles Completed in 14052ms
2523 silly saveTree nj-attorney@1.0.0
2523 silly saveTree ├── dom7@2.1.5
2523 silly saveTree ├── framework7-icons@3.0.1
2523 silly saveTree ├── framework7-svelte@5.7.12
2523 silly saveTree ├─┬ framework7@5.7.12
2523 silly saveTree │ └── template7@1.4.2
2523 silly saveTree └── template7@1.4.2
2524 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '...:"^0.24.0","mocha":"3'
2524 verbose stack     at JSON.parse (<anonymous>)
2524 verbose stack     at parseJson (/usr/local/Cellar/node@12/12.18.3/lib/node_modules/npm/node_modules/json-parse-better-errors/index.js:7:17)
2524 verbose stack     at /usr/local/Cellar/node@12/12.18.3/lib/node_modules/npm/node_modules/node-fetch-npm/src/body.js:96:50
2524 verbose stack     at runMicrotasks (<anonymous>)
2524 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:97:5)


✖ Error installing NPM Dependencies
npm ERR! Unexpected end of JSON input while parsing near '...:"^0.25.3","mocha":"3'
```

**Comment by srbala** [comment]
it turns out its my local npm cache issue. after clearing cache, apps starts working
